"""initial schema

Revision ID: 5d6c6ab024b5
Revises: 
Create Date: 2026-03-01 14:34:09.402655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d6c6ab024b5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_users_email'), 'staff_users', ['email'], unique=True)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('home_city', sa.String(length=255), nullable=True),
    sa.Column('preferred_budget', sa.String(length=50), nullable=True),
    sa.Column('travel_style', sa.String(length=255), nullable=True),
    sa.Column('dietary_requirements', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['staff_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_reference_code'), 'clients', ['reference_code'], unique=True)
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('budget', sa.String(length=50), nullable=True),
    sa.Column('distance', sa.String(length=50), nullable=True),
    sa.Column('include_photos', sa.Boolean(), nullable=True),
    sa.Column('include_dining', sa.Boolean(), nullable=True),
    sa.Column('include_attractions', sa.Boolean(), nullable=True),
    sa.Column('photos_per_day', sa.Integer(), nullable=True),
    sa.Column('restaurants_per_day', sa.Integer(), nullable=True),
    sa.Column('attractions_per_day', sa.Integer(), nullable=True),
    sa.Column('photo_interests', sa.String(length=500), nullable=True),
    sa.Column('cuisines', sa.String(length=500), nullable=True),
    sa.Column('attraction_cats', sa.String(length=500), nullable=True),
    sa.Column('accommodation', sa.String(length=500), nullable=True),
    sa.Column('raw_photos', sa.Text(), nullable=True),
    sa.Column('raw_restaurants', sa.Text(), nullable=True),
    sa.Column('raw_attractions', sa.Text(), nullable=True),
    sa.Column('approved_photo_indices', sa.Text(), nullable=True),
    sa.Column('approved_restaurant_indices', sa.Text(), nullable=True),
    sa.Column('approved_attraction_indices', sa.Text(), nullable=True),
    sa.Column('final_html', sa.Text(), nullable=True),
    sa.Column('colors', sa.String(length=500), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['staff_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_client_id'), 'trips', ['client_id'], unique=False)
    op.create_index(op.f('ix_trips_session_id'), 'trips', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_session_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_client_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_clients_reference_code'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_staff_users_email'), table_name='staff_users')
    op.drop_table('staff_users')
    # ### end Alembic commands ###
